release:
  &release 4.15.0

releases:
  - *release
  - 3.10.1
  - 2.4.2

fontawesome:
  version:
    4.6.3

immutable:
  version:
    3.8.1

react:
  version:
    15.3.1

sass:
  sass_dir:
    assets/css

exclude:
  - Gemfile
  - LICENSE
  - "*.md"

include:
  - _redirects

incremental: true
