release:
  &release 4.15.0

releases:
  - *release
  - 3.10.1
  - 2.4.2

brand_color: "#3492ff"
description: "A JavaScript utility library delivering consistency, modularity, performance, & extras."
incremental: true
safe: false

sass:
  sass_dir:
    assets/css

vendor: {
  "css": [
    "https://unpkg.com/font-awesome@4.6.3/css/font-awesome.min.css"
  ],
  "font": [
    "https://unpkg.com/font-awesome@4.6.3/fonts/fontawesome-webfont.woff2?v=4.6.3"
  ],
  "js": [
    "https://embed.runkit.com/",
    "https://unpkg.com/fuse.js@2.5.0/src/fuse.min.js",
    "https://unpkg.com/immutable@3.8.1/dist/immutable.min.js",
    "https://unpkg.com/react@15.3.1/dist/react.min.js",
    "https://unpkg.com/react-dom@15.3.1/dist/react-dom.min.js"
  ]
}

exclude:
  - icons/favicon-16x16.png
  - node_modules
  - Gemfile
  - gulpfile.js
  - icons.js
  - LICENSE
  - "package.json"
  - "*.log"
  - "*.md"
  - "*.toml"

include:
  - _headers
  - _redirects
